artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ajaychaudhary8104/Datasets/raw/refs/heads/main/ride_marketplace.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:

  root_dir: artifacts/data_validation

  unzip_data_dir: artifacts/data_ingestion

  STATUS_FILE: artifacts/data_validation/status.txt

  REPORT_FILE: artifacts/data_validation/validation_report.json

  STATS_REPORT_FILE: artifacts/data_validation/dataset_statistics.json

  DRIFT_REPORT_FILE: artifacts/data_validation/drift_report.json
