artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/ajaychaudhary8104/Datasets/raw/refs/heads/main/ride_marketplace.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:

  root_dir: artifacts/data_validation

  unzip_data_dir: artifacts/data_ingestion

  STATUS_FILE: artifacts/data_validation/status.txt

  REPORT_FILE: artifacts/data_validation/validation_report.json

  STATS_REPORT_FILE: artifacts/data_validation/dataset_statistics.json

  DRIFT_REPORT_FILE: artifacts/data_validation/drift_report.json

data_preprocessing:

  root_dir: artifacts/data_preprocessing

  input_data_path: artifacts/data_ingestion

  output_data_path: artifacts/data_preprocessing/preprocessed_rides.parquet

  preprocessing_report_path: artifacts/data_preprocessing/preprocessing_report.json

  outlier_method: iqr

  outlier_iqr_multiplier: 1.5

  numerical_imputation_method: median

  categorical_imputation_method: mode

  optimize_memory: true

  save_format: parquet    

feature_engineering:

  root_dir: artifacts/feature_engineering

  input_data_path: artifacts/data_preprocessing/preprocessed_rides.parquet

  output_data_path: artifacts/feature_engineering/featured_data.parquet

  feature_report_path: artifacts/feature_engineering/feature_report.json 

  original_feature_count: 45  

feature_store:

  root_dir: artifacts/feature_store
  
  feature_columns_path: config/feature_columns.yaml

  feature_repo_path: src/ride_demand_forecasting_and_marketplace_optimization/feature_repo

  offline_feature_path: artifacts/feature_engineering/featured_data.parquet

  registry_path: src/ride_demand_forecasting_and_marketplace_optimization/feature_repo/registry.db

  online_store_path: src/ride_demand_forecasting_and_marketplace_optimization/feature_repo/online_store.db

  feature_store_yaml_path: src/ride_demand_forecasting_and_marketplace_optimization/feature_repo/feature_store.yaml

  project_name: ride_marketplace_forecasting

  feature_view_name: ride_marketplace_features

  feature_service_name: forecast_service

  entity_name: zone_timestamp

  join_key: zone_timestamp_key

  timestamp_column: timestamp

  start_date: 2022-12-01-T00:00:00

  end_date: 2022-12-31-T23:59:59  
